### ISSUE TITLE
CODE IS NOT WORKING

### ISSUE THREAD

**Issue by jenapss** [pixochi/instagram-content-publishing-react-app#1]
Hello,

I ran the code with proper APP ID and successfully could login to Facebook, but when I press "Submit" button to post into my Instagram it shows me this error

P.S I already converted my IG account to a business account and linked FB Business page with IF Business account.

![Screen Shot 2022-11-30 at 1 52 25 PM](https://user-images.githubusercontent.com/43576850/204778265-57045739-ba92-4273-afd7-03ab753404d6.png)

WHO ELSE ENCOUNTERED THIS ISSUE?

**Comment by pixochi** [comment]
Hi @jenapss, could you check what's the content of `response`?

**Comment by jenapss** [comment]
Alright, I could handle this and everything worked well. Thank you. The solution was to add more additional permissions to scope.
